### ISSUE TITLE
got error when state no set

### ISSUE THREAD

**Issue by geminiyellow** [adambrgmn/react-oauth-flow#21]
README say the `state` is no required.

> 

Prop | Type | Required
-- | -- | --
state | object | no

but when i run the example and remove the state, i got this.

```
Uncaught SyntaxError: Unexpected token u in JSON at position 0
```

when checked the source, i found this

https://github.com/adambrgmn/react-oauth-flow/blob/f7cb4949a106a1f574eb12dc1bdf4f8b7f71ecb2/src/OauthReceiver/index.js#L64

when `state` is `undefined`, boom...

**Comment by adambrgmn** [comment]
Oh that was a strange bug from my side! As I mentioned in your other issue (#22) I don't have much time at hand right now. But I would welcome a PR from your side if you feel into it.

Otherwise I will probably have more free time in the end of may when I can look in to this.

Have you encountered anything else while trying out this module? Anything that can be worked on or improved?
